// Generated by CoffeeScript 1.6.3
(function() {
  var currentTime, incrementTime, initialSetup, isChrome, prettyTime, setupClickEvent, showTime, showTimeOnce, updateTime;

  prettyTime = function(time) {
    return "" + (time.getHours()) + ":" + (time.getMinutes()) + ":" + (time.getSeconds());
  };

  updateTime = function(time) {
    return $("#time").text(prettyTime(time));
  };

  currentTime = null;

  initialSetup = function() {
    currentTime = new Date();
    if (isChrome()) {
      console.debug("in chrome");
      incrementTime(3600);
    }
    return updateTime(currentTime);
  };

  incrementTime = function(seconds) {
    return currentTime = new Date(currentTime.getTime() + seconds * 1000);
  };

  showTimeOnce = function() {
    incrementTime(1);
    return updateTime(currentTime);
  };

  showTime = function() {
    return setInterval(showTimeOnce, 1000);
  };

  setupClickEvent = function() {
    return $("a#add-minute").click(function() {
      return incrementTime(60);
    });
  };

  isChrome = function() {
    var res;
    res = navigator.userAgent.toLowerCase().indexOf('chrome');
    console.debug(navigator.userAgent.toLowerCase());
    console.debug(res);
    return res > -1;
  };

  $(initialSetup);

  $(showTime);

  $(setupClickEvent);

}).call(this);
